// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Token struct {
	Value string `json:"value"`
}

type UserDetails struct {
	UserID    int64   `json:"user_id"`
	Username  string  `json:"username"`
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	Gender    *string `json:"gender"`
	Password  string  `json:"password"`
	Status    int     `json:"status"`
}

type UserInput struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
