// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Friendship struct {
	Username   string
	FriendName string
}

type User struct {
	Username string
	Name     string
	Password string
}

type UserDetail struct {
	UserID    int32
	Username  sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    sql.NullString
	Password  sql.NullString
	Status    sql.NullInt32
}
