// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const authenticateUser = `-- name: AuthenticateUser :one
SELECT username, name, password FROM users
WHERE username = $1
AND password = $2
`

type AuthenticateUserParams struct {
	Username string
	Password string
}

func (q *Queries) AuthenticateUser(ctx context.Context, arg AuthenticateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, authenticateUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.Username, &i.Name, &i.Password)
	return i, err
}

const createFriendShip = `-- name: CreateFriendShip :one
INSERT INTO friendships(username, friend_name)
VALUES ($1, $2)
RETURNING username, friend_name
`

type CreateFriendShipParams struct {
	Username   string
	FriendName string
}

func (q *Queries) CreateFriendShip(ctx context.Context, arg CreateFriendShipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, createFriendShip, arg.Username, arg.FriendName)
	var i Friendship
	err := row.Scan(&i.Username, &i.FriendName)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, password)
VALUES ($1, $2, $3)
RETURNING username, name, password
`

type CreateUserParams struct {
	Username string
	Name     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Name, arg.Password)
	var i User
	err := row.Scan(&i.Username, &i.Name, &i.Password)
	return i, err
}

const deleteDetails = `-- name: DeleteDetails :one
DELETE FROM user_details
WHERE username = $1
RETURNING user_id, username, first_name, last_name, gender, password, status
`

func (q *Queries) DeleteDetails(ctx context.Context, username sql.NullString) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, deleteDetails, username)
	var i UserDetail
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Password,
		&i.Status,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE username = $1
AND password = $2
RETURNING username, name, password
`

type DeleteUserParams struct {
	Username string
	Password string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.Username, &i.Name, &i.Password)
	return i, err
}

const getFriends = `-- name: GetFriends :many
SELECT username, name, password
FROM users AS u
WHERE u.username IN   (
    SELECT f1.friend_name
    FROM friendships AS f1
    WHERE f1.username = $1
    UNION
    SELECT f2.username
    FROM friendships AS f2
    WHERE f2.friend_name = $1
)
`

func (q *Queries) GetFriends(ctx context.Context, username string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Username, &i.Name, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT username, name, password FROM users
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(&i.Username, &i.Name, &i.Password)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT username, name, password FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Username, &i.Name, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFriendship = `-- name: RemoveFriendship :one
DELETE FROM friendships
WHERE (username = $1 AND friend_name = $2) OR (username = $2 AND friend_name = $1)
RETURNING username, friend_name
`

type RemoveFriendshipParams struct {
	Username   string
	FriendName string
}

func (q *Queries) RemoveFriendship(ctx context.Context, arg RemoveFriendshipParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, removeFriendship, arg.Username, arg.FriendName)
	var i Friendship
	err := row.Scan(&i.Username, &i.FriendName)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    password = $2,
    name = $3
WHERE
    username = $1
RETURNING username, name, password
`

type UpdateUserParams struct {
	Username string
	Password string
	Name     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.Password, arg.Name)
	var i User
	err := row.Scan(&i.Username, &i.Name, &i.Password)
	return i, err
}
