// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
)

type User struct {
	ID       int32
	Username string
	Name     string
	Password string
}

type UserDetail struct {
	UserID    int32
	Username  sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    sql.NullString
	Password  sql.NullString
	Status    sql.NullInt32
}
