// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package pg

import (
	"context"
	"database/sql"
)

const authenticateUser = `-- name: AuthenticateUser :one
SELECT id, username, name, password FROM users
WHERE username = $1
AND password = crypt($1, password)
`

func (q *Queries) AuthenticateUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, authenticateUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name, password)
VALUES ($1, $2, crypt($3, gen_salt('bf')))
RETURNING id, username, name, password
`

type CreateUserParams struct {
	Username string
	Name     string
	Crypt    interface{}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Name, arg.Crypt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const deleteDetails = `-- name: DeleteDetails :one
DELETE FROM user_details
WHERE username = $1
RETURNING user_id, username, first_name, last_name, gender, password, status
`

func (q *Queries) DeleteDetails(ctx context.Context, username sql.NullString) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, deleteDetails, username)
	var i UserDetail
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Password,
		&i.Status,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE username = $1
AND password = crypt($1, password)
RETURNING id, username, name, password
`

func (q *Queries) DeleteUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, name, password FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, name, password FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
